language: go
os: linux
dist: xenial
env:
  global:
    - HUGO_RELEASE=0.53
install:
  - "./.travis/get_deps.sh"
script:
  - "./.travis/build_all.sh"
  - cp CNAME public
after_success:
  - scp -r public hugo@47.91.224.140:~/pages
deploy:
  local_dir: public
  repo: rhubard/rhubard.github.io
  target_branch: master
  provider: pages
  strategy: git
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  email: 18734141014@qq.com
  name: rhubard
