language: go
os: linux
dist: xenial
env:
  global:
    - HUGO_RELEASE=0.53
before_install:
  - openssl aes-256-cbc -K $encrypted_0836b113fae8_key -iv $encrypted_0836b113fae8_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 47.91.224.140\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - "./.travis/get_deps.sh"
script:
  - "./.travis/build_all.sh"
  - cp CNAME public
after_success:
  - scp -o stricthostkeychecking=no -r public hugo@47.91.224.140:~/pages
deploy:
  local_dir: public
  repo: rhubard/rhubard.github.io
  target_branch: master
  provider: pages
  strategy: git
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  email: 18734141014@qq.com
  name: rhubard
addons:
  ssh_known_hosts: 47.91.224.140
